### ISSUE TITLE
Broken Link in workshop instructions [TrackerControl Protocol - Thomas Huchon Feedback]

### ISSUE THREAD

**Issue by Shalf** [hestiaAI/data-catalog#11]
In https://github.com/hestiaAI/data-catalog/blob/main/workshop/how-to-export-data-from-trackercontrol.md, **Step 6**:

Dead link: in the particular case of TH,  the link should be https://digipower.academy/bubble/th-participant/experience/tracker-control#load-data
**What is the good way to get the generic and particular cases right in this protocol?**

We need this up-to-date for the TH particular case for his first course on Monday Oct 4th.
Biz-wise, I shared with him the right link already.

**Comment by Shalf** [comment]
Thanks for the quick fix.
Since this is the generic, public protocol, everytime someone **not** from the TH Bubble will try and use it, we'll come back at it :)

**Comment by valentinoli** [comment]
You can change it easily on GitHub by clicking the pencil icon

**Comment by Shalf** [comment]
Indeed. Would have done that if that was solving the issue.

Your fix doesn't solve the need for it to be Evergreen (in particular when we have at least 2 different clients -- TH at Sc Po, Brown -- using it and sending participants to it simultaneously).

Did a temp fix.

**Comment by valentinoli** [comment]
Ok
It was not clear to me this is what you were asking for. I feel like this issue should have been an internal biz dev issue
